version: '3.8'

services:
  app:
    container_name: ktu-grade-aggregator
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./logs:/usr/src/app/log
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV:-production}
      - NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED:-0}
    restart: unless-stopped
