services:
  app:
    container_name: ktu-results-aggregator
    image: ghcr.io/rithask/ktu-results-aggregator:latest
    ports:
      - "3001:3001"
    volumes:
      - ./logs:/app/logs
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV:-production}
      - NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED:-0}
      - TZ=${TZ:-Asia/Kolkata}
    restart: unless-stopped
